/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KLZ de Panama
 */
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class TetrisForm extends javax.swing.JFrame {

    /**
     * Creates new form TetrisForm
     */
    
	int finalBlockType = 0;
	int startingX = 0;
	int startingY = 0;
	int currentX = 0;
	int currentY = 0;
	int width = 0;
	int height = 0;
	
	
	String projPath = System.getProperty("user.dir");
        JLabel blockLabel = new JLabel();
	
        
	public TetrisForm() {
        initComponents();
    }
    
	
    public void addBlock(String fileLocation, int xCoord, int yCoord)
    {
    	String addedBlock = fileLocation;
        ImageIcon blockPic = new ImageIcon(addedBlock);
    	blockLabel.setIcon(blockPic);
        LayeredPane.moveToFront(blockLabel);
        
        startingX = 39*xCoord;
        startingY = 39*yCoord;
        currentX = startingX;
        currentY = startingY;
        width = blockPic.getIconWidth();
        height = blockPic.getIconHeight();
        setPosition(blockLabel, startingX, startingY);
        
        blockLabel.setVisible(true);
    }
    
    
    public void setPosition(JLabel blok, int x, int y){
    	blok.setBounds(x, y, width, height);
    }
    
    
    public void resetPosition(JLabel blok){
    
    blok.setBounds(startingX, startingY, width, height);
    }
    
    
    public void moveLeft(){
        
    }   
    
    public void moveRight(){
        
    }
    
    public void drop(){
        
    }
    
    public void tickDown(){
    	
    	currentY = currentY + 10;
        blockLabel.setBounds(currentX, currentY, width, height);
    }
    
    
    public void placeBlock(){
    
    	resetPosition(blockLabel);
    	JLabel finalBlock = new JLabel();
    	ImageIcon blockPic = new ImageIcon(projPath + "\\art\\IbeamG.png");
    	finalBlock.setIcon(blockPic);
        LayeredPane.add(finalBlock);
        LayeredPane.moveToFront(finalBlock);
        
        
        finalBlock.setBounds(currentX, currentY, width, height);
        blockLabel.setVisible(false);
    	
    }
    
    
    public void setShape(int blockType, int startX, int startY){
    	
    	if (blockType == 1)
    	{
    		finalBlockType = 1;
    		String block = projPath + "\\art\\Ibeam.png";
    		addBlock(block, startX, startY);
    	}
    	
    	else if (blockType == 2){
    		finalBlockType = 2;
    		String block = projPath + "\\art\\Jbeam.png";
    		addBlock(block, startX, startY);
    	}
    	
    	else if (blockType == 3){
    		finalBlockType = 3;
    		String block = projPath + "\\art\\Lbeam.png";
    		addBlock(block, startX, startY);
    	}
    	
    	else if (blockType == 4){
    		finalBlockType = 4;
    		String block = projPath + "\\art\\Square.png";
    		addBlock(block, startX, startY);
    	}
    	
    	else if (blockType == 5){
    		finalBlockType = 5;
    		String block = projPath + "\\art\\Sbeam.png";
    		addBlock(block, startX, startY);    		
    	}
    	
    	else if (blockType == 6){
    		finalBlockType = 2;
    		String block = projPath + "\\art\\Tbeam.png";
    		addBlock(block, startX, startY);
    	}
    	
    	else if (blockType == 7){
    		finalBlockType = 2;
    		String block = projPath + "\\art\\Zbeam.png";
    		addBlock(block, startX, startY);
    	}
    	    
    }
    
    
    public void makeFrame(){
    setSize(984, 930);
    setVisible(true);
    LayeredPane.add(blockLabel);
    blockLabel.setVisible(false);
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredPane = new javax.swing.JLayeredPane();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout LayeredPaneLayout = new javax.swing.GroupLayout(LayeredPane);
        LayeredPane.setLayout(LayeredPaneLayout);
        LayeredPaneLayout.setHorizontalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        LayeredPaneLayout.setVerticalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        getContentPane().add(LayeredPane);
        LayeredPane.setBounds(340, 50, 400, 790);

        backgroundImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\KLZ de Panama\\Documents\\GitHub\\CSCI-1302-Project-4\\art\\background_0Piece.png")); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 980, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TetrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TetrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TetrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TetrisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TetrisForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JLabel backgroundImage;
    // End of variables declaration//GEN-END:variables
}
