/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KLZ de Panama
 */
public class TetrisMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form TetrisMainMenu
     */
    public TetrisMainMenu() {
        initComponents();
    }
    
    int choice;
    TetrisBoard TB;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PlayButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        noPane = new javax.swing.JRadioButton();
        PButton = new javax.swing.JRadioButton();
        FPButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					PlayButtonActionPerformed(evt);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Tetris!");

        buttonGroup1.add(noPane);
        noPane.setSelected(true);
        noPane.setText("Classic");
        noPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPaneActionPerformed(evt);
            }
        });

        buttonGroup1.add(PButton);
        PButton.setText("1 Preview Pane");
        PButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(FPButton);
        FPButton.setText("4 Preview Panes");
        FPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(noPane)
                .addGap(156, 156, 156)
                .addComponent(PButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(FPButton)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPane)
                    .addComponent(PButton)
                    .addComponent(FPButton))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:
    	if (choice == 1){
            TB = new TetrisBoard(1);
            TB.createForm();
            setVisible(false);
			
            double timer = System.currentTimeMillis();
            
            while (!TB.gameFinished()){
            	
            	TB.moveLeft();
        		TB.moveRight();
        		TB.twist();
        		TB.instantDrop();
            	
	            if(System.currentTimeMillis() - timer > 400){
	            	TB.tick();
				
	            	timer = System.currentTimeMillis();
	            }
            }
        }
    	else if (choice == 2){
            TB = new TetrisBoard(2);
            TB.createForm();
            setVisible(false);
			
            double timer = System.currentTimeMillis();
            
            while (!TB.gameFinished()){
            	
            	TB.moveLeft();
        		TB.moveRight();
        		TB.twist();
        		TB.instantDrop();
            	
	            if(System.currentTimeMillis() - timer > 400){
	            	TB.tick();
				
	            	timer = System.currentTimeMillis();
	            }
            }
        }
    	else if (choice == 3){
            TB = new TetrisBoard(4);
            TB.createForm();
            setVisible(false);
			
            double timer = System.currentTimeMillis();
            
            while (!TB.gameFinished()){
            	
            	TB.moveLeft();
        		TB.moveRight();
        		TB.twist();
        		TB.instantDrop();
            	
	            if(System.currentTimeMillis() - timer > 400){
	            	TB.tick();
				
	            	timer = System.currentTimeMillis();
	            }
            }
        }
    }

    public void makeFrame(){
        choice = 1;
        setVisible(true);
    }
    
    private void noPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPaneActionPerformed
        // TODO add your handling code here:
        choice = 1;
    }//GEN-LAST:event_noPaneActionPerformed

    private void PButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonActionPerformed
        // TODO add your handling code here:
        choice = 2;
    }//GEN-LAST:event_PButtonActionPerformed

    private void FPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPButtonActionPerformed
        // TODO add your handling code here:
        choice = 3;
    }//GEN-LAST:event_FPButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FPButton;
    private javax.swing.JRadioButton PButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton noPane;
    // End of variables declaration//GEN-END:variables
}
