/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KLZ de Panama
 */
public class TTTMainMenu extends javax.swing.JFrame {
    
    String diff;
    boolean human;
    TTTBoard ttt;
    /**
     * Creates new form TTTMainMenu
     */
    public TTTMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        playButton = new javax.swing.JButton();
        HumanButton = new javax.swing.JRadioButton();
        ComputerButton = new javax.swing.JRadioButton();
        DifficultyBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        ButtonGroup.add(HumanButton);
        HumanButton.setText("Human");
        HumanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButtonActionPerformed(evt);
            }
        });

        ButtonGroup.add(ComputerButton);
        ComputerButton.setText("Computer");
        ComputerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerButtonActionPerformed(evt);
            }
        });

        DifficultyBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toddler", "Intermediate", "War Games", "Self Lock", "" }));
        DifficultyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficultyBoxActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic-Tac-Toe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(HumanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComputerButton)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(DifficultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumanButton)
                    .addComponent(ComputerButton))
                .addGap(53, 53, 53)
                .addComponent(DifficultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        
        if (human == false){
            if (diff.equalsIgnoreCase("Toddler")){
                ttt.makeFrame("Computer", 0);
            }
        
        
                   else if (diff.equalsIgnoreCase("Intermediate")){
                ttt.makeFrame("Computer", 1);
            }
        
    
                       else if (diff.equalsIgnoreCase("War Games")){
                ttt.makeFrame("Computer", 2);
            }
        

                   else if (diff.equalsIgnoreCase("Self Lock")){
                ttt.makeFrame("Computer", 3);
            }
        }
        
        else
            ttt.makeFrame();
        
    }//GEN-LAST:event_playButtonActionPerformed

    private void ComputerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputerButtonActionPerformed
        DifficultyBox.setVisible(true);
        human = false;
        diff = "Toddler";
    }//GEN-LAST:event_ComputerButtonActionPerformed

    private void HumanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButtonActionPerformed
        // TODO add your handling code here:
        DifficultyBox.setVisible(false);
        human = true;
    }//GEN-LAST:event_HumanButtonActionPerformed

    private void DifficultyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficultyBoxActionPerformed
        // TODO add your handling code here:
        String diff = (String)DifficultyBox.getSelectedItem();
    }//GEN-LAST:event_DifficultyBoxActionPerformed

public void makeFrame(){
    setVisible(true);
    human = true;
    DifficultyBox.setVisible(false);
    ttt = new TTTBoard();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JRadioButton ComputerButton;
    private javax.swing.JComboBox DifficultyBox;
    private javax.swing.JRadioButton HumanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
